version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: brainiac_integration_test
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 2s
      retries: 10
      timeout: 2s

  tests:
    image: golang:1.24
    container_name: brainiac_tests
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "go mod tidy && go test ./... -v"